# -*- coding: utf-8 -*-
"""CCT111H5 - Assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VkSCw9NWkuW38QVNGAkZArfeqZo1vLOW
"""

print("Introducing the Environmental Impact Calculator, where your life choices on the environment input can be seen on full display!")
# First, I asked the user the amount of distance he travelled.
while True: # I initially use a while loop to make sure the user enters a positive digit, as the distance travelled cannot be negative. Therefore, if the user does not meet that condition,the loop will keep going until the user gives a positive digit.
    number = float(input("Enter the total distance traveled in kilometers: ")) # Number is equal to the input the user puts -> Total distance travelled.
    if number <= 0: # An if statement saying if the number is less or equal to 0, it will print error
        print("Error, enter a positive number.")
    else: #Otherwise, if the condition is met, the loop will break.
        break
# Secondly, I ask the user the mode of transportation
while True: # I used another loop to make sure the user inputs the 3 specific modes of transportation.
    transportation = input("Enter your transportation mode (cars, bicycles or public transportation): ") # The user enters the type of transportation used
    if transportation not in ["cars", "bicycles", "public transportation"]: #An if statement saying if the transportations are not cars, bicycles or public transportations, it will print error.
        print("Error, enter cars, bicycles or public transportation")
    else: #Otherwise, if the condition is met, the loop will break
      break
# Thirdly, I input the amount of emission in each transportation
if transportation == "cars": #An if statement saying if the user inputs the transportation is equal to the cars, then the rate of emission for this transportation is 0.12
  rate = 0.12
elif transportation == "bicycles": #An if statement saying if the user inputs the transportation is equal to the bicycles, then the rate of emission for this transportation is 0
  rate = 0
elif transportation == "public transportation": #An if statement saying if the user inputs the transportation is equal to the public transportation, then the rate of emission for this transportation is 0.08
  rate = 0.08
# Lastly, using the distance and rate, I print each result
carbon = float(number) * rate # The amount of carbon is the distanced travelled multiplied by the rate of emission.
print("Transportation:", transportation) #This prints the results of the mode of transportation used
print("Distance Travelled:", number, "km") #This prints the result of the number of distanced travelled in km
print("Carbon emission:", carbon, "kilograms of CO2") #This prints the total amount of carbon emission used.

print("Thank you for using Environmental Impact Calculator!")